# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4ef5f4d370fc099eb613f0bd04ca5c69"
name = "test-app-remix"
handle = "test-app-remix-11"
application_url = "https://newsletters-personal-moderator-time.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-3c08b97b.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://newsletters-personal-moderator-time.trycloudflare.com/auth/callback",
  "https://newsletters-personal-moderator-time.trycloudflare.com/auth/shopify/callback",
  "https://newsletters-personal-moderator-time.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
